<?php
include 'meat.php';

class Goat extends meat
{
public function weight()
{
    parent::weight(); // TODO: Change the autogenerated stub
    print '<article class ="picture">';
    print '<img src ="goat.jpg" alt ="meat" width ="40%" height ="20%">';
    //print '<button id ="like"><img src = "like.png" alt = "Like" width = "20px" height ="20px"></button>';
    //print '<button id = "dislike"><img src = "dislike.png" alt = "Like" width = "15px" height ="15px"></button>';
    print '<select name="Weight">';
    print '</select>';
    print '<input type="submit" id ="button" value ="Add to basket"</input>';
    print '</article>';
}
}
$goat = new Goat(1200,"Kazakhstan");
$goat->weight();